name: Scaffold Microservice from Port

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload"
        type: string

jobs:
  scaffold-and-create:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Port Payload
        id: port_vars
        run: |
          PAYLOAD='${{ github.event.inputs.port_payload }}'
          echo "REPO_NAME=$(echo $PAYLOAD | jq -r '.payload.properties.repo_name')" >> $GITHUB_ENV
          echo "PORT_RUN_ID=$(echo $PAYLOAD | jq -r '.context.runId')" >> $GITHUB_ENV

      - name: Create New Repository
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          gh repo create ANHILOUS/${{ env.REPO_NAME }} --public --add-readme

      - name: Report Success
        if: always()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ env.PORT_RUN_ID }}
          logMessage: "Successfully built ${{ env.REPO_NAME }}! 🚀"
